### ISSUE TITLE
Installation instructions don't work

### ISSUE THREAD

**Issue by Huluk** [sn127/tackler#20]
I tried to follow the "Minimal setup" instructions using v0.9.0. It's listed that I need a file `./txns/journal.txn`, which I created using `touch`. First run failed because I don't have a config. I scrolled a bit further from the minimal setup section and copied the config from recommended setup instead. Now I get a parse error `Txn Parse Error: [/my/system/paths/txns/journal.txn] msg: null`. I assume the manual is just out of date but I also don't know how to set up this system so that it does not crash immediately.

**Comment by jaa127** [comment]
Hello,  thanks for the report.

The journal can not be empty, so that's hard error by desing. However, the error message is really poor.

Try to populate same content for journal, or copy some of the test files for quick test. One starting point could be this: https://github.com/sn127/tackler/blob/stable/tests/reporting/ok/reporting.txn
If you haven't setup accounts.conf then remember to provide `--accounts.strict=false`

Syntax of journal is documented here: https://github.com/sn127/tackler/blob/stable/docs/journal.adoc

It's odd that default configuration discovery did not work. There is embedded configuration within jar, which should be sufficient for minimal setup.  Actually, congratulations, you found a bug: #21.

**Comment by jaa127** [comment]
Or if you like to play with GIT there is more complete setup instructions for that (GIT is not mandatory by any means): https://github.com/sn127/tackler/blob/stable/docs/git-storage.adoc

**Comment by jaa127** [comment]
Hopefully commit 45d93099b7db693748506604bfdacc336ce13fd3 and 3e9e3fed0268b71468a79cf4943f566895a47825 clarify initial setup so that it is easier to create working demo setup. 

I also verified that the embedded configuration actually works. There is an error which warns that embedded configuration is used. However, embedded configuration contains valid defaults for demo setup, but probably is not something which would be used in production.

**Comment by Huluk** [comment]
Thank you for the quick fix! The new instructions are indeed much easier to understand :) Everything seems to work now, but I'll keep my eyes open for bugs of course!

**Comment by jaa127** [comment]
Glad to hear that it's better now. Be warned that ANTLR (parser which used to parse journal) is quite unforgiving regarding syntax errors in journal and tackler's error messages are neither stellar.  Hopefully it won't be too frustrating. =]

There will be new release of tackler in near future. It will be  mostly about transaction filters (for server/client API) but those could also be defined from CLI https://github.com/sn127/tackler/blob/stable/CHANGELOG.adoc
 
Happy accounting, and if you find bugs or other oddities, please report those!
